import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";
import "./globals.css";
import SiteNavbar from "@/components/site-navbar";
import { SiteFooter } from "@/components/site-footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <SiteNavbar />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
